fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.3.2"
    ruby:
      repo: "git://github.com/boxen/puppet-ruby"
      ref:  "8.1.4"
    repository:
      repo: "git://github.com/boxen/puppet-repository"
      ref:  "2.3.0"
    boxen: 
      repo: "git://github.com/boxen/puppet-boxen"
      ref:  "3.4.2"
    gcc: 
      repo: "git://github.com/boxen/puppet-gcc"
      ref:  "1.0.0"
    homebrew: 
      repo: "git://github.com/boxen/puppet-homebrew"
      ref:  "1.1.2"
    xquartz: 
      repo: "git://github.com/boxen/puppet-xquartz"
      ref:  "1.1.0"
    autoconf: 
      repo: "git://github.com/boxen/puppet-autoconf"
      ref:  "1.0.0"
    openssl: 
      repo: "git://github.com/boxen/puppet-openssl"
      ref:  "1.0.0"
    java: 
      repo: "git://github.com/boxen/puppet-java"
      ref:  "1.2.0"
    module-data:
      repo: "git://github.com/ripienaar/puppet-module-data"
      ref:  "0.0.3"
  symlinks:
    homesick: '#{source_dir}'
